/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Szpontniki's Firmware API
 * API of a LED-managing microcontroller developed by Szpontniki.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

/**
 * @minItems 3
 * @maxItems 3
 * @items.minimum 0
 * @items.maximum 255
 */
export type Color = number[];

export type ColorPixelsRequestPixelsItem = {
  x: number;
  y: number;
  /**
     * @minItems 3
     * @maxItems 3
     * @items.minimum 0
     * @items.maximum 255
     */
  color: number[];
};

export interface ColorPixelsRequest {
  pixels: ColorPixelsRequestPixelsItem[];
}

export type CurrentStateResponsePixelsItem = {
  x: number;
  y: number;
  /**
     * @minItems 3
     * @maxItems 3
     * @items.minimum 0
     * @items.maximum 255
     */
  color: number[];
};

export interface CurrentStateResponse {
  pixels?: CurrentStateResponsePixelsItem[];
}

export type DisplayColorPixelsBodyPixelsItem = {
  x: number;
  y: number;
  /**
     * @minItems 3
     * @maxItems 3
     * @items.minimum 0
     * @items.maximum 255
     */
  color: number[];
};

export type DisplayColorPixelsBody = {
  pixels: DisplayColorPixelsBodyPixelsItem[];
};

export type GetDisplayState200PixelsItem = {
  x: number;
  y: number;
  /**
     * @minItems 3
     * @maxItems 3
     * @items.minimum 0
     * @items.maximum 255
     */
  color: number[];
};

export type GetDisplayState200 = {
  pixels?: GetDisplayState200PixelsItem[];
};

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type displayColorPixelsResponse200 = {
  data: void
  status: 200
}

export type displayColorPixelsResponse400 = {
  data: void
  status: 400
}

export type displayColorPixelsResponseSuccess = (displayColorPixelsResponse200) & {
  headers: Headers;
};
export type displayColorPixelsResponseError = (displayColorPixelsResponse400) & {
  headers: Headers;
};

export type displayColorPixelsResponse = (displayColorPixelsResponseSuccess | displayColorPixelsResponseError)

export const getDisplayColorPixelsUrl = () => {




  return `/display/color-pixels`
}

/**
 * @summary Allows coloring display's pixels.
 */
export const displayColorPixels = async (displayColorPixelsBody: DisplayColorPixelsBody, options?: RequestInit): Promise<displayColorPixelsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getDisplayColorPixelsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(displayColorPixelsBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: displayColorPixelsResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as displayColorPixelsResponse
}





export const getDisplayColorPixelsMutationKey = () => ['displayColorPixels'] as const;

export const getDisplayColorPixelsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof displayColorPixels>>, TError,DisplayColorPixelsMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof displayColorPixels>>, TError,DisplayColorPixelsMutationVariables, TContext> => {

const mutationKey = getDisplayColorPixelsMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof displayColorPixels>>, DisplayColorPixelsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  displayColorPixels(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DisplayColorPixelsMutationResult = NonNullable<Awaited<ReturnType<typeof displayColorPixels>>>
    export type DisplayColorPixelsMutationBody = DisplayColorPixelsBody
    export type DisplayColorPixelsMutationError = void
    export type DisplayColorPixelsMutationVariables = {data: DisplayColorPixelsBody}

    /**
 * @summary Allows coloring display's pixels.
 */
export const useDisplayColorPixels = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof displayColorPixels>>, TError,DisplayColorPixelsMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof displayColorPixels>>,
        TError,
        DisplayColorPixelsMutationVariables,
        TContext
      > => {
      return useMutation(getDisplayColorPixelsMutationOptions(options), queryClient);
    }

export type getDisplayStateResponse200 = {
  data: GetDisplayState200
  status: 200
}

export type getDisplayStateResponse400 = {
  data: void
  status: 400
}

export type getDisplayStateResponseSuccess = (getDisplayStateResponse200) & {
  headers: Headers;
};
export type getDisplayStateResponseError = (getDisplayStateResponse400) & {
  headers: Headers;
};

export type getDisplayStateResponse = (getDisplayStateResponseSuccess | getDisplayStateResponseError)

export const getGetDisplayStateUrl = () => {




  return `/display/current-state`
}

/**
 * @summary Returns the current state of the display.
 */
export const getDisplayState = async ( options?: RequestInit): Promise<getDisplayStateResponse> => {

  const res = await fetch(getGetDisplayStateUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDisplayStateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDisplayStateResponse
}





export const getGetDisplayStateQueryKey = () => {
    return [
    `/display/current-state`
    ] as const;
    }


export const getGetDisplayStateQueryOptions = <TData = Awaited<ReturnType<typeof getDisplayState>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDisplayStateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDisplayState>>> = ({ signal }) => getDisplayState({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDisplayStateQueryResult = NonNullable<Awaited<ReturnType<typeof getDisplayState>>>
export type GetDisplayStateQueryError = void


export function useGetDisplayState<TData = Awaited<ReturnType<typeof getDisplayState>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDisplayState>>,
          TError,
          Awaited<ReturnType<typeof getDisplayState>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDisplayState<TData = Awaited<ReturnType<typeof getDisplayState>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDisplayState>>,
          TError,
          Awaited<ReturnType<typeof getDisplayState>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDisplayState<TData = Awaited<ReturnType<typeof getDisplayState>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the current state of the display.
 */

export function useGetDisplayState<TData = Awaited<ReturnType<typeof getDisplayState>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDisplayState>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDisplayStateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
