/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Szpontniki's Auxiliary API
 * Auxiliary API providing image and video processing capabilities developed by Szpontniki.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

export interface ProessImageRequest {
  width: number;
  height: number;
  imageBase64: string;
}

export interface ProcessImageResponse {
  imageBase64: string;
}

export type ProcessImageBody = {
  width: number;
  height: number;
  imageBase64: string;
};

export type ProcessImage200 = {
  imageBase64: string;
};

export type processImageResponse200 = {
  data: ProcessImage200
  status: 200
}

export type processImageResponse400 = {
  data: void
  status: 400
}

export type processImageResponseSuccess = (processImageResponse200) & {
  headers: Headers;
};
export type processImageResponseError = (processImageResponse400) & {
  headers: Headers;
};

export type processImageResponse = (processImageResponseSuccess | processImageResponseError)

export const getProcessImageUrl = () => {




  return `/process/image`
}

/**
 * @summary Processes an image into a set resolution.
 */
export const processImage = async (processImageBody: ProcessImageBody, options?: RequestInit): Promise<processImageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getProcessImageUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(processImageBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: processImageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as processImageResponse
}





export const getProcessImageMutationKey = () => ['processImage'] as const;

export const getProcessImageMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processImage>>, TError,ProcessImageMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof processImage>>, TError,ProcessImageMutationVariables, TContext> => {

const mutationKey = getProcessImageMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processImage>>, ProcessImageMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  processImage(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProcessImageMutationResult = NonNullable<Awaited<ReturnType<typeof processImage>>>
    export type ProcessImageMutationBody = ProcessImageBody
    export type ProcessImageMutationError = void
    export type ProcessImageMutationVariables = {data: ProcessImageBody}

    /**
 * @summary Processes an image into a set resolution.
 */
export const useProcessImage = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processImage>>, TError,ProcessImageMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof processImage>>,
        TError,
        ProcessImageMutationVariables,
        TContext
      > => {
      return useMutation(getProcessImageMutationOptions(options), queryClient);
    }
